### ISSUE TITLE
Remove entryPoint seem broke example 

### ISSUE THREAD

**Issue by iamgqb** [webgpu/webgpufundamentals#86]
This commit remove all entry points. https://github.com/webgpu/webgpufundamentals/commit/abe4e2e8b9cc4eeb52b3ba4ed1d24a6d64263ec8

And now all sample on https://webgpufundamentals.org/ is not working.

for example the first article
<img width="1406" alt="image" src="https://github.com/webgpu/webgpufundamentals/assets/2213424/e4b1b549-8c26-43bf-bc33-e9cca713712f">

the error message indicate the entryPoint is required
<img width="1243" alt="image" src="https://github.com/webgpu/webgpufundamentals/assets/2213424/b2b09afa-7c18-473f-bb5c-f4d8b6ea4198">

add the entryPoint , the example working
<img width="1407" alt="image" src="https://github.com/webgpu/webgpufundamentals/assets/2213424/23d1c07d-e9f7-4b93-a785-f2f95a4932c5">

**Comment by greggman** [comment]
Sorry, please upgrade to chrome v121 (assuming you're using Chrome). I will add a message asap

**Comment by greggman** [comment]
I added a msg

<img width="1143" alt="Screenshot 2024-01-25 at 11 43 16" src="https://github.com/webgpu/webgpufundamentals/assets/234804/087dc608-bdc9-4c44-8e52-8ffe966077fe">

Note: This is a non-breaking change to the WebGPU spec. It used to be that `entryPoint: 'nameOfEntryPoint'` was required but the spec changed so that if there is only a single entry point of the correct type (`@vertex`, `@fragment`, `@compute` then you don't need to specify an entry point. WebGPU will use the single entry point. Non-breaking means the old unchanged examples still work. The ones with `entryPoint: 'vs',` etc...

My guess is, not specifying the entryPoint will become the most common way to use WebGPU as it's less tedious and since this site is about teaching WebGPU it seemed best to switch it to this likely more common way.  Unfortunately that means requiring version 121 or greater of Chrome.  Safari Technology Preview already supports this feature.  Firefox Nightly has other issues but should also support WebGPU enough to run most of the samples here soon.

**Comment by iamgqb** [comment]
wow，nice feature！I will close this issue.

Thank you for your response and tip.
